import type { IconDefinition, Library } from '@fortawesome/fontawesome-svg-core'
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faApple,
  faFacebookF,
  faGoogle,
  faXTwitter
} from '@fortawesome/free-brands-svg-icons'
import { faHeart as farHeart } from '@fortawesome/free-regular-svg-icons'
import {
  faArrowLeft,
  faArrowRight,
  faArrowTrendDown,
  faArrowTrendUp,
  faArrowsRotate,
  faAt,
  faBan,
  faBarcode,
  faBars,
  faBell,
  faBox,
  faBriefcase,
  faBuilding,
  faCalendar,
  faCalendarCheck,
  faCalendarDay,
  faCalendarDays,
  faCalendarPlus,
  faCalendarXmark,
  faCamera,
  faCartShopping,
  faCashRegister,
  faChair,
  faChartColumn,
  faChartLine,
  faChartPie,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCirclePlay,
  faCirclePlus,
  faCircleQuestion,
  faClipboardList,
  faClock,
  faClockRotateLeft,
  faCode,
  faCommentDots,
  faCompass,
  faCopy,
  faCreditCard,
  faDiamondTurnRight,
  faDoorOpen,
  faDollarSign,
  faDumbbell,
  faEllipsis,
  faEllipsisVertical,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFilePen,
  faFilter,
  faGear,
  faGlobe,
  faGrip,
  faGauge,
  faHammer,
  faHandshake,
  faHeart,
  faIdCard,
  faImage,
  faInbox,
  faLayerGroup,
  faLifeRing,
  faLink,
  faListCheck,
  faLocationDot,
  faLock,
  faMagnifyingGlass,
  faMap,
  faMedal,
  faMicrophone,
  faMinus,
  faMoneyBillWave,
  faMugSaucer,
  faMusic,
  faMoon,
  faPalette,
  faPen,
  faPenToSquare,
  faPercent,
  faPhone,
  faPlus,
  faQrcode,
  faScaleBalanced,
  faRightFromBracket,
  faRightToBracket,
  faShareNodes,
  faShield,
  faShieldHalved,
  faSliders,
  faSpinner,
  faStar,
  faStore,
  faShop,
  faSun,
  faTags,
  faThumbtack,
  faTicket,
  faTrash,
  faTriangleExclamation,
  faTruck,
  faTowerBroadcast,
  faUpRightFromSquare,
  faUser,
  faUserCheck,
  faUserGear,
  faUserPlus,
  faUsers,
  faUserShield,
  faUtensils,
  faVideo,
  faWallet,
  faXmark,
  faMobileScreenButton,
  faPersonChalkboard,
  faCircleXmark,
  faMoneyBillTrendUp
} from '@fortawesome/free-solid-svg-icons'

/** Lucide-style keys (`i-lucide-*`) used across the app → Font Awesome solid icons */
const lucideIconMap: Record<string, IconDefinition> = {
  'i-lucide-activity': faChartLine,
  'i-lucide-alert-triangle': faTriangleExclamation,
  'i-lucide-arrow-right': faArrowRight,
  'i-lucide-bar-chart': faChartColumn,
  'i-lucide-bell': faBell,
  'i-lucide-building': faBuilding,
  'i-lucide-calendar': faCalendar,
  'i-lucide-calendar-check': faCalendarCheck,
  'i-lucide-calendar-clock': faClockRotateLeft,
  'i-lucide-calendar-days': faCalendarDays,
  'i-lucide-calendar-x': faCalendarXmark,
  'i-lucide-camera': faCamera,
  'i-lucide-check': faCheck,
  'i-lucide-check-circle': faCircleCheck,
  'i-lucide-chevron-down': faChevronDown,
  'i-lucide-chevron-up': faChevronUp,
  'i-lucide-clock': faClock,
  'i-lucide-coffee': faMugSaucer,
  'i-lucide-credit-card': faCreditCard,
  'i-lucide-dollar-sign': faDollarSign,
  'i-lucide-edit': faPenToSquare,
  'i-lucide-envelope': faEnvelope,
  'i-lucide-eye': faEye,
  'i-lucide-eye-off': faEyeSlash,
  'i-lucide-filter': faFilter,
  'i-lucide-hammer': faHammer,
  'i-lucide-handshake': faHandshake,
  'i-lucide-heart': faHeart,
  'i-lucide-history': faClockRotateLeft,
  'i-lucide-image': faImage,
  'i-lucide-inbox': faInbox,
  'i-lucide-info': faCircleInfo,
  'i-lucide-layers': faLayerGroup,
  'i-lucide-life-buoy': faLifeRing,
  'i-lucide-link': faLink,
  'i-lucide-loader-2': faSpinner,
  'i-lucide-lock': faLock,
  'i-lucide-lock-keyhole': faLock,
  'i-lucide-log-in': faRightToBracket,
  'i-lucide-log-out': faRightFromBracket,
  'i-lucide-mail': faEnvelope,
  'i-lucide-map': faMap,
  'i-lucide-map-pin': faLocationDot,
  'i-lucide-menu': faBars,
  'i-lucide-mic-2': faMicrophone,
  'i-lucide-minus': faMinus,
  'i-lucide-monitor-play': faCirclePlay,
  'i-lucide-monitor-smartphone': faMobileScreenButton,
  'i-lucide-moon': faMoon,
  'i-lucide-more-horizontal': faEllipsis,
  'i-lucide-more-vertical': faEllipsisVertical,
  'i-lucide-pencil': faPen,
  'i-lucide-phone': faPhone,
  'i-lucide-pie-chart': faChartPie,
  'i-lucide-plus': faPlus,
  'i-lucide-presentation': faPersonChalkboard,
  'i-lucide-qr-code': faQrcode,
  'i-lucide-refresh-cw': faArrowsRotate,
  'i-lucide-scale': faScaleBalanced,
  'i-lucide-scan-line': faBarcode,
  'i-lucide-search': faMagnifyingGlass,
  'i-lucide-settings': faGear,
  'i-lucide-shield': faShield,
  'i-lucide-shield-check': faShieldHalved,
  'i-lucide-shield-x': faBan,
  'i-lucide-sliders-horizontal': faSliders,
  'i-lucide-store': faStore,
  'i-lucide-sun': faSun,
  'i-lucide-ticket': faTicket,
  'i-lucide-ticket-percent': faPercent,
  'i-lucide-trash-2': faTrash,
  'i-lucide-trending-up': faArrowTrendUp,
  'i-lucide-truck': faTruck,
  'i-lucide-user': faUser,
  'i-lucide-user-check': faUserCheck,
  'i-lucide-user-plus': faUserPlus,
  'i-lucide-users': faUsers,
  'i-lucide-video': faVideo,
  'i-lucide-wallet': faWallet,
  'i-lucide-x': faXmark,
  'i-lucide-x-circle': faCircleXmark,
  'i-lucide-layout-dashboard': faGauge,
  'i-lucide-clipboard-list': faClipboardList,
  'i-lucide-list-todo': faListCheck,
  'i-lucide-badge-check': faCircleCheck
}

/** Former Material Symbols names (underscore) → Font Awesome */
const materialIconMap: Record<string, IconDefinition> = {
  add: faPlus,
  add_circle: faCirclePlus,
  admin_panel_settings: faUserGear,
  alternate_email: faAt,
  arrow_back: faArrowLeft,
  arrow_forward: faArrowRight,
  business: faBriefcase,
  business_center: faBriefcase,
  calendar_month: faCalendarDays,
  calendar_today: faCalendarDay,
  cancel: faXmark,
  chat: faCommentDots,
  check_circle: faCircleCheck,
  chevron_left: faChevronLeft,
  chevron_right: faChevronRight,
  circle: faCircle,
  close: faXmark,
  code: faCode,
  confirmation_number: faTicket,
  content_copy: faCopy,
  delete: faTrash,
  directions: faDiamondTurnRight,
  dashboard: faGauge,
  edit: faPenToSquare,
  edit_calendar: faCalendarDays,
  edit_document: faFilePen,
  error_outline: faCircleExclamation,
  event: faCalendar,
  event_available: faCalendarCheck,
  event_busy: faCalendarXmark,
  event_seat: faChair,
  event_upcoming: faCalendarPlus,
  expand_more: faChevronDown,
  explore: faCompass,
  favorite: faHeart,
  favorite_border: farHeart,
  filter_list: faFilter,
  fitness_center: faDumbbell,
  grid_view: faGrip,
  group: faUsers,
  group_add: faUserPlus,
  groups: faUsers,
  help_outline: faCircleQuestion,
  how_to_reg: faIdCard,
  info: faCircleInfo,
  inventory_2: faBox,
  location_on: faLocationDot,
  mail: faEnvelope,
  menu: faBars,
  mic: faMicrophone,
  meeting_room: faDoorOpen,
  logout: faRightFromBracket,
  military_tech: faMedal,
  monetization_on: faMoneyBillTrendUp,
  more_horiz: faEllipsis,
  more_vert: faEllipsisVertical,
  notifications: faBell,
  open_in_new: faUpRightFromSquare,
  palette: faPalette,
  payments: faCreditCard,
  paid: faMoneyBillWave,
  person: faUser,
  person_add: faUserPlus,
  photo_camera: faCamera,
  point_of_sale: faCashRegister,
  progress_activity: faSpinner,
  public: faGlobe,
  push_pin: faThumbtack,
  qr_code_2: faQrcode,
  qr_code_scanner: faQrcode,
  rate_review: faCommentDots,
  remove: faMinus,
  restaurant: faUtensils,
  schedule: faClock,
  search: faMagnifyingGlass,
  security_update_good: faUserShield,
  sensors: faTowerBroadcast,
  share: faShareNodes,
  shield: faShield,
  shopping_cart: faCartShopping,
  storefront: faShop,
  star: faStar,
  tune: faSliders,
  trending_down: faArrowTrendDown,
  trending_up: faArrowTrendUp,
  visibility: faEye,
  visibility_off: faEyeSlash,
  warning: faTriangleExclamation,
  music_note: faMusic,
  sell: faTags,
  activity_history: faClockRotateLeft
}

const brandIcons = [faGoogle, faFacebookF, faXTwitter, faApple]

function collectUniqueDefinitions(): IconDefinition[] {
  const seen = new Set<IconDefinition>()
  const out: IconDefinition[] = []
  for (const icon of [
    ...Object.values(lucideIconMap),
    ...Object.values(materialIconMap),
    ...brandIcons,
    faCircleQuestion
  ]) {
    if (!seen.has(icon)) {
      seen.add(icon)
      out.push(icon)
    }
  }
  return out
}

/** Optional: register all icons for `FaIcon icon="user"`-style usage where applicable */
export function registerAppIcons(lib: Library = library): void {
  lib.add(...collectUniqueDefinitions())
}

export function resolveAppIcon(name: string): IconDefinition {
  if (!name) return faCircleQuestion
  if (name.startsWith('i-lucide-')) {
    return lucideIconMap[name] ?? faCircleQuestion
  }
  return materialIconMap[name] ?? lucideIconMap[name] ?? faCircleQuestion
}

export function appIconShouldSpin(name: string): boolean {
  return name === 'i-lucide-loader-2' || name === 'progress_activity'
}

export const socialBrandIcons = {
  google: faGoogle,
  facebook: faFacebookF,
  twitter: faXTwitter,
  apple: faApple
} as const
